artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  #source_url :
  local_data_file : artifacts/data_ingestion/data.csv 

data_validation:
  root_dir : artifacts/data_validation
  local_data_file : artifacts/data_ingestion/data.csv 
  STATUS_FILE: STATUS.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/forest.csv